GET http://localhost:3001/books HTTP/1.1
###

POST http://localhost:3001/books HTTP/1.1
content-type: application/json

{"title":"Harry Potter tap 4"}
###

PUT http://localhost:3001/books/3 HTTP/1.1
content-type: application/json

{"title":"Harry Potter tap 3"}
###

DELETE  http://localhost:3001/books/5 HTTP/1.1
content-type: application/json



